02 file service
garrichello/script-007-tasks pull request #2
Opened 2022-05-31 10:51 UTC by garrichello

Task 2: File service

2022-05-31 11:27 UTC, maxx27 requested changes

2022-05-31 11:27 UTC, maxx27 commented on server/FileService.py
> +    result["content"] = content
Если open не пройдёт, то что будет?

2022-05-31 11:27 UTC, maxx27 commented on server/FileService.py
> +    with open(filename, "r") as f:
Использовать binary

2022-05-31 11:27 UTC, maxx27 commented on server/FileService.py
> +    if isinstance(content, str):
Используем binary без проверки

2022-05-31 11:27 UTC, maxx27 commented on server/test_fileservice/conftest.py
> +def get_file_info(file_name: str):
Использовать версию из FileServer
+ высталять время создания/модификации вручную

2022-05-31 11:27 UTC, maxx27 commented on server/test_fileservice/conftest.py
> +    return [dict(name="letters.txt", data="abcdefghijklmnopqrstuvwxyz"), dict(name="digits.txt", data="1234567890")]
Эти данные одинаково запишутся в 'w' и 'wb'. Для проверки использовать '\n' или Unicode (🔥)

2022-05-31 11:27 UTC, maxx27 commented on server/test_fileservice/conftest.py
> +    os.chdir(str(tmp_path))
вынести в отдельную фикстуру

2022-05-31 11:27 UTC, maxx27 commented on server/test_fileservice/test_createfile.py
> +        print(file_full_info)
убрать

2022-05-31 11:27 UTC, maxx27 commented on server/test_fileservice/test_getfiles.py
> +            if file_meta in two_files_meta:
file_meta_is_present.append(file_meta in two_files_meta)

2022-05-31 11:32 UTC, maxx27 requested changes

2022-05-31 11:32 UTC, maxx27 commented on main.py
> +    print(f"Задан рабочий каталог: {args.data_directory}")
убрать

2022-05-31 11:32 UTC, maxx27 commented on main.py
> +def main(args: argparse.Namespace):
идеально протестировать main.py

2022-05-31 16:01 UTC, garrichello commented on server/test_fileservice/conftest.py
> +    os.chdir(str(tmp_path))
Done

2022-05-31 16:02 UTC, garrichello commented on server/test_fileservice/test_createfile.py
> +        print(file_full_info)
Done

2022-05-31 16:03 UTC, garrichello commented on server/test_fileservice/test_getfiles.py
> +            if file_meta in two_files_meta:
Done

2022-05-31 16:04 UTC, garrichello commented on main.py
> +    print(f"Задан рабочий каталог: {args.data_directory}")
Done

2022-05-31 17:31 UTC, garrichello commented on server/FileService.py
> +    result["content"] = content
Добавил инициализацию:
```python
    result = get_file_metadata(filename)
    content = bytes()
    with open(filename, "rb") as f:
        content = f.read()
    result["content"] = content
```
Но сдаётся мне, что если _open()_ или _read()_ крашнутся, то функция вывалится с соответствующим исключением ещё до строки _result["content"] = content_

2022-05-31 17:31 UTC, garrichello commented on server/FileService.py
> +    with open(filename, "r") as f:
Done

2022-05-31 17:31 UTC, garrichello commented on server/FileService.py
> +    if isinstance(content, str):
Done

2022-05-31 17:33 UTC, garrichello commented on server/test_fileservice/conftest.py
> +    return [dict(name="letters.txt", data="abcdefghijklmnopqrstuvwxyz"), dict(name="digits.txt", data="1234567890")]
Заменил на _random.randbytes(100)_. Теперь в тестовые файлы складывается куча случайных bytes.

2022-05-31 18:21 UTC, garrichello commented on server/test_fileservice/conftest.py
> +def get_file_info(file_name: str):
Done.
Вручную выставляется имя файла, дата модификации и размер. Время создания извлекается через _os.path.getctime()_.
В принципе, можно и время создания задавать через win32 API, но, мне кажется, это будет уже перебор. :)

2022-06-01 08:36 UTC, garrichello commented on main.py
> +def main(args: argparse.Namespace):
В первом приближении - Done :)

2022-06-02 07:19 UTC, merged